package com.cucumber.aps

enum class ErrorCode(codeName: String) {
    ERR_LICENSE_INVALID("ERR_LICENSE_INVALID"),
    ERR_LICENSE_LIMITED("ERR_LICENSE_LIMITED"),
    ERR_TOKEN_AUTH_INVALID("ERR_TOKEN_AUTH_INVALID"),
    ERR_LICENSE_DISABLED("ERR_LICENSE_DISABLED"),
    ERR_IP_AUTH_PROVIDER_INVALID("ERR_IP_AUTH_PROVIDER_INVALID"),
    CSAP_AUTH_NOT_AUTHORIZED("CSAP_AUTH_NOT_AUTHORIZED"),
    CSAP_TOKEN_INVALID("CSAP_TOKEN_INVALID"),
    CSAP_IP_INVALID("CSAP_IP_INVALID"),
}